language: lisp

env:
  global:
    - CIM_HOME="$HOME/.cim"
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    # - LISP=ecl

install:
  - sudo apt-get install texinfo
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/develop/install.sh | sh;
    fi
  - cl -l clx -l cl-ppcre -Q

before_script:
  - ./autogen.sh
  - ./configure

script:
  - make
